# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ master, development, '**-RC' ]
    paths-ignore:
      - 'README.md'
      - '.github/**/*.md'
      - '.github/workflows/autoMerge.yml'
      - '.github/workflows/calibreapp-image-actions.yml'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/conflicts.yml'
      - '.github/workflows/label-issue.yml'
      - '.github/workflows/label-pr.yml'
      - '.github/workflows/no-response.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/remove-outdated-labels.yml'
      - '.github/workflows/stale.yml'
      - '.github/workflows/updateSite.yml'

  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: Build

    # As this action runs on every push to the default branch and uses quite a lot of resources (both minutes and caches),
    # only run it in the FreeTubeApp/FreeTube repository to avoid unnecessary GitHub Actions usage/billing in forks.
    # Still allow manually triggering the workflow.
    # If a fork does need this workflow to run on every push to the default branch, they can change this condition in their fork to include their repository.
    if: github.repository == 'FreeTubeApp/FreeTube' || github.event_name == 'workflow_dispatch'

    permissions:
      actions: write
      contents: read

    strategy:
      matrix:
        node-version: [24.x]
        runtime:
          - win-x64
        include:
        - runtime: win-x64
          os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      with:
        persist-credentials: false

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #v7.0.0
      with:
        node-version: ${{ matrix.node-version }}
        package-manager-cache: false

    - name: Install pnpm
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 #v6.0.9
      with:
        version: 10
        cache: false

    - name: Get pnpm cache directory
      id: cache_dir
      shell: bash
      run: |
        {
          echo 'cache_dir<<EOF'
          pnpm store path
          echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Restore pnpm cache
      id: restore_cache
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 #v6.1.0
      with:
        key: ${{ format('node-cache-{0}-{1}-pnpm-{2}', runner.os, runner.arch, hashFiles('pnpm-lock.yaml')) }}
        path: ${{ steps.cache_dir.outputs.cache_dir }}

    - run: pnpm run ci
      shell: bash
    - run: pnpm run lint
      shell: bash
    - name: Set version number
      id: versionNumber
      shell: bash
      run: |
        original_version="$(jq -r '.version' package.json)"
        version="$original_version"

        lower_case_ref="$(echo -E "$GITHUB_REF" | tr '[:upper:]' '[:lower:]')"

        if [[ "$lower_case_ref" == *development* ]]; then
          version="${original_version}-nightly-${GITHUB_RUN_NUMBER}"
        elif [[ "$lower_case_ref" == *rc* ]]; then
          version="${original_version}-RC-${GITHUB_RUN_NUMBER}"
        fi

        package_json="$(jq --arg version "$version" '.version = $version' package.json)"

        echo -E "$package_json" > package.json
        echo "version=${version}" >> "$GITHUB_OUTPUT"

    - name: Install libarchive-tools
      if: startsWith(matrix.os, 'ubuntu')
      shell: bash
      run: |
        sudo apt update
        sudo apt -y install libarchive-tools

    - name: Build x64 with Node.js ${{ matrix.node-version}}
      if: contains(matrix.runtime, 'x64')
      shell: bash
      run: pnpm run build

    - name: Upload Windows x64 .7z Artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
      if: startsWith(matrix.os, 'windows') && startsWith(matrix.runtime, 'win-x64')
      with:
        name: freetube-${{ steps.versionNumber.outputs.version }}-win-x64-portable.7z
        path: build/freetube-${{ steps.versionNumber.outputs.version }}-win.7z

    - name: Save pnpm cache
      uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 #v6.1.0
      # Only save the cache if we weren't able to restore an existing one above
      if: steps.restore_cache.outputs.cache-primary-key != steps.restore_cache.outputs.cache-matched-key
      with:
        key: ${{ steps.restore_cache.outputs.cache-primary-key }}
        path: ${{ steps.cache_dir.outputs.cache_dir }}
